version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: crudcompanydb
      POSTGRES_USER: company_user
      POSTGRES_PASSWORD: pass123!
    ports:
      - 5432:5432

  app:
    build: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/crudcompanydb
      SPRING_DATASOURCE_USERNAME: company_user
      SPRING_DATASOURCE_PASSWORD: pass123!